---
- name: Install and Configure Rclone
  hosts: [terraform_all]
  become: no
  gather_facts: no

  vars:
    rclone_binary_path: "/usr/bin/rclone"
    rclone_config_dir: "/root/.config/rclone"
    b2_account_name: "b2"
    mount_point: "/mnt/b2"

  tasks:

  - name: update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: install core packages
    apt:
      name:
        - net-tools
        - tmux
      update_cache: yes
  
  - name: install Rclone and dependencies
    apt:
      name:
        - fuse
        - rclone
      state: present
      update_cache: yes

  - name: Ensure destination dir exists
    file:
      # path: "{{ dest_path | dirname }}"
      path: "{{ rclone_config_dir }}"
      state: directory

  - name: Configure Rclone
    template:
      src: templates/rclone.conf.j2
      dest: "{{ rclone_config_dir }}/rclone.conf"
      mode: '0600'
    notify: Restart Rclone service

  - name: Create mount point
    file:
      path: "{{ mount_point }}"
      state: directory
      mode: '0755'

  - name: Create systemd service file
    template:
      src: templates/rclone.service.j2
      dest: "/etc/systemd/system/rclone.service"
      mode: '0644'
    notify: Reload systemd daemon

  - name: Enable and start Rclone service
    systemd:
      name: rclone.service
      state: started
      enabled: yes
      daemon_reload: yes

  handlers:
  - name: Restart Rclone service
    systemd:
      name: rclone.service
      state: restarted

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes

  - name: Reboot the machine
    reboot:
      msg: "Rebooting machine after initial setup"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 60
      test_command: uptime