plugin: cloud.terraform.terraform_provider
project_path: ./terraform
# Terraform binary (available in the $PATH) or full path to the binary.
binary_path: terraform

backend_type: s3

backend_config:
  endpoints: s3 = {{ lookup('env', 'b2_s3_endpoint' }}
  region: region
  key: "{{ lookup('env', 'b2_tfstate_key' }}"
  bucket: "{{ lookup('env', 'b2_tfstate_bucket' }}"
  access_key: "{{ lookup('env', 'b2_application_key_id' }}"
  secret_key: "{{ lookup('env', 'b2_application_key' }}"
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_region_validation: true
  skip_s3_checksum: true